# Generated by Django 4.0.1 on 2022-01-26 13:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BinanceApiModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Account Name')),
                ('apiKey', models.CharField(max_length=255, verbose_name='API Key')),
                ('apiSecretKey', models.CharField(max_length=255, verbose_name='API Secret Key')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PositionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pair', models.CharField(max_length=255, verbose_name='Pair')),
                ('side', models.CharField(choices=[('short', 'SHORT'), ('long', 'LONG')], max_length=255, verbose_name='Side')),
                ('bam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='binanceAPI.binanceapimodel')),
            ],
        ),
    ]
