# Generated by Django 4.0.1 on 2022-01-26 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('binanceAPI', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='positionmodel',
            name='isOpen',
            field=models.BooleanField(default=True, verbose_name='Is Open'),
        ),
    ]
