# Generated by Django 4.0.2 on 2022-03-27 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('binanceAPI', '0004_positionmodel_firsttpcloseprecentage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='KlineIndicatorModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open', models.FloatField(verbose_name='Open')),
                ('high', models.FloatField(verbose_name='High')),
                ('low', models.FloatField(verbose_name='Low')),
                ('close', models.FloatField(verbose_name='Close')),
                ('bigDonUB', models.FloatField(verbose_name='Big Don Upper Band')),
                ('bigDonLB', models.FloatField(verbose_name='Big Don Lower Band')),
                ('smallDonUB', models.FloatField(verbose_name='Small Don Upper Band')),
                ('smallDonLB', models.FloatField(verbose_name='Small Don Lower Band')),
                ('ema', models.FloatField(verbose_name='EMA')),
            ],
        ),
        migrations.CreateModel(
            name='PairModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pair', models.CharField(max_length=255, verbose_name='Pair')),
            ],
        ),
    ]
