# Generated by Django 4.0.2 on 2022-03-27 23:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('binanceAPI', '0005_klineindicatormodel_pairmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='klineindicatormodel',
            name='pair',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='binanceAPI.pairmodel'),
            preserve_default=False,
        ),
    ]
