# Generated by Django 4.0.2 on 2022-03-28 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('binanceAPI', '0006_klineindicatormodel_pair'),
    ]

    operations = [
        migrations.AddField(
            model_name='pairmodel',
            name='bigDonLen',
            field=models.IntegerField(default=0, verbose_name='Big Don Length'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pairmodel',
            name='emaLen',
            field=models.IntegerField(default=0, verbose_name='EMA Length'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pairmodel',
            name='smallDonLen',
            field=models.IntegerField(default=0, verbose_name='Small Don Length'),
            preserve_default=False,
        ),
    ]
