# Generated by Django 4.0.2 on 2022-03-28 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('binanceAPI', '0007_pairmodel_bigdonlen_pairmodel_emalen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='klineindicatormodel',
            name='closeTime',
            field=models.DateTimeField(default='1999-05-25', verbose_name='Close Time'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='klineindicatormodel',
            name='openTime',
            field=models.DateTimeField(default='1999-05-25', verbose_name='Open Time'),
            preserve_default=False,
        ),
    ]
