# Generated by Django 4.0.2 on 2022-03-31 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('binanceAPI', '0008_klineindicatormodel_closetime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pairmodel',
            name='rrRatio',
            field=models.FloatField(default=0, verbose_name='Risk/Reward Ratio'),
            preserve_default=False,
        ),
    ]
