# Generated by Django 4.0.2 on 2022-03-31 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('binanceAPI', '0010_pairmodel_inpos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pairmodel',
            name='inPos',
            field=models.CharField(blank=True, default='NONE', max_length=255, null=True, verbose_name='In Position'),
        ),
    ]
