# Generated by Django 4.0.2 on 2022-03-31 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('binanceAPI', '0011_alter_pairmodel_inpos'),
    ]

    operations = [
        migrations.AddField(
            model_name='pairmodel',
            name='stopPrice',
            field=models.FloatField(blank=True, null=True, verbose_name='Stop Price'),
        ),
    ]
