# Generated by Django 4.0.2 on 2022-03-31 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('binanceAPI', '0012_pairmodel_stopprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='pairmodel',
            name='tpPrice',
            field=models.FloatField(blank=True, null=True, verbose_name='Take Profit Price'),
        ),
    ]
