# Generated by Django 4.0.2 on 2022-03-31 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('binanceAPI', '0013_pairmodel_tpprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='positionmodel',
            name='trailingClose',
            field=models.BooleanField(verbose_name='Trailing Close'),
        ),
    ]
