# Generated by Django 4.0.2 on 2022-04-02 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('binanceAPI', '0015_pairmodel_trailingclose_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PositionModel',
            new_name='StrategyModel',
        ),
    ]
