# Generated by Django 4.0.2 on 2022-04-02 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('binanceAPI', '0016_rename_positionmodel_strategymodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategymodel',
            name='interval',
            field=models.CharField(choices=[('15m', '15m'), ('30m', '30m'), ('1h', '1h'), ('2h', '2h'), ('4h', '4h'), ('1d', '1d')], default='1m', max_length=255, verbose_name='Interval'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='strategymodel',
            name='pair',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='binanceAPI.pairmodel'),
        ),
    ]
