# Generated by Django 4.0.2 on 2022-04-02 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('binanceAPI', '0017_strategymodel_interval_alter_strategymodel_pair'),
    ]

    operations = [
        migrations.CreateModel(
            name='PairPosModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(blank=True, null=True, verbose_name='Quantity')),
                ('bam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='binanceAPI.binanceapimodel')),
                ('pair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='binanceAPI.pairmodel')),
            ],
        ),
    ]
