# Generated by Django 4.0.2 on 2022-04-02 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('binanceAPI', '0018_pairposmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='binanceapimodel',
            name='isActive',
            field=models.BooleanField(default=True, verbose_name='Is Active?'),
            preserve_default=False,
        ),
    ]
