# Generated by Django 4.0.2 on 2022-04-02 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('binanceAPI', '0019_binanceapimodel_isactive'),
    ]

    operations = [
        migrations.AddField(
            model_name='pairmodel',
            name='interval',
            field=models.CharField(choices=[('15m', '15m'), ('30m', '30m'), ('1h', '1h'), ('2h', '2h'), ('4h', '4h'), ('1d', '1d')], default='30m', max_length=255, verbose_name='Interval'),
            preserve_default=False,
        ),
    ]
