# Generated by Django 4.0.2 on 2022-04-03 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('binanceAPI', '0020_pairmodel_interval'),
    ]

    operations = [
        migrations.AddField(
            model_name='binanceapimodel',
            name='hedgeMode',
            field=models.BooleanField(default=False, verbose_name='Hedge Mode'),
            preserve_default=False,
        ),
    ]
