# Generated by Django 4.0.2 on 2022-04-03 23:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('binanceAPI', '0021_binanceapimodel_hedgemode'),
    ]

    operations = [
        migrations.AddField(
            model_name='pairmodel',
            name='coolDownDate',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Cooldown Date'),
            preserve_default=False,
        ),
    ]
