# Generated by Django 4.0.2 on 2022-04-03 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('binanceAPI', '0022_pairmodel_cooldowndate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pairmodel',
            name='coolDownDate',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Cooldown Date'),
        ),
    ]
