# Generated by Django 4.0.2 on 2022-04-05 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('binanceAPI', '0024_rename_cooldowndate_pairmodel_cooldowndate'),
    ]

    operations = [
        migrations.AddField(
            model_name='pairmodel',
            name='entryPrice',
            field=models.FloatField(blank=True, null=True, verbose_name='Entry Price'),
        ),
        migrations.AddField(
            model_name='pairmodel',
            name='firstTpPrice',
            field=models.FloatField(blank=True, null=True, verbose_name='First Take Profit Price'),
        ),
        migrations.AddField(
            model_name='pairmodel',
            name='isTpTaken',
            field=models.BooleanField(default=False, verbose_name='Is First Take Profit Taken?'),
        ),
    ]
