# Generated by Django 4.0.2 on 2022-04-11 23:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('binanceAPI', '0025_pairmodel_entryprice_pairmodel_firsttpprice_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pairmodel',
            name='firstTpPrice',
        ),
        migrations.RemoveField(
            model_name='pairmodel',
            name='isTpTaken',
        ),
        migrations.CreateModel(
            name='PairTpModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tpRate', models.FloatField(verbose_name='TP Ratio')),
                ('tpPrice', models.FloatField(blank=True, null=True, verbose_name='TP Price')),
                ('isTaken', models.BooleanField(default=False, verbose_name='Is TP Taken?')),
                ('pair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='binanceAPI.pairmodel')),
            ],
        ),
    ]
