# Generated by Django 4.0.1 on 2022-01-26 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SignalModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date')),
                ('pair', models.CharField(max_length=255, verbose_name='Pair')),
                ('side', models.CharField(max_length=255, verbose_name='Side')),
                ('entryOne', models.FloatField(verbose_name='Entry 1')),
                ('entryTwo', models.FloatField(verbose_name='Entry 2')),
                ('stoploss', models.FloatField(verbose_name='Stoploss')),
                ('isOpen', models.BooleanField(blank=True, default=True, null=True, verbose_name='Is Open')),
            ],
        ),
        migrations.CreateModel(
            name='SignalTargetsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Target Name')),
                ('price', models.FloatField(verbose_name='Target Price')),
                ('signal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signal_model', to='botsignal.signalmodel')),
            ],
        ),
    ]
