# Generated by Django 4.0.4 on 2022-05-15 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paperTrade', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaperPositionQuantityModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(verbose_name='Quantity')),
                ('paperPosition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paperTrade.paperpositionmodel')),
            ],
        ),
    ]
